version: "3"

services:
  api:
    build:
      context: .
    container_name: api
    image: omidebrahimi/nette-blog
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/home/php/api
      - ./:/var/www/api
      - ./php-local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    networks:
      - api-network
    environment:
      - COMPOSER_MEMORY_LIMIT=-1

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
    networks:
      - api-network

  nginx:
    image: nginx:1.21-alpine
    container_name: api-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - api-network

  phpmyadmin:
    image: phpmyadmin:5.1-fpm-alpine
    container_name: phpmyadmin
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - PMA_HOST=mysql
    ports:
      - "8090:80"
    depends_on:
      - mysql
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
